name: Set version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'
    - name: Install bumpver
      run: pip install bumpver
    - name: Check dry versioning with bumpver
      run: bumpver update -n --set-version "${{ github.event.inputs.version }}"
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: user_info
        fetch: false
        message: 'Set version v${{ github.event.inputs.version }}'
        pathspec_error_handling: exitImmediately
        push: true
        tag: 'v${{ github.event.inputs.version }}'
        tag_push: '--force'
